### ISSUE TITLE
Just get an empty json

### ISSUE THREAD

**Issue by stellanhaglund** [chrispalazzolo/fbxasciitojs#1]
```
var parser = require("fbxasciitojs");

options = {
  parseComments: true,
  verbose: true,
  logging: true,
  returnJSON: true,
  saveJSON: true
}

// Async call 
parser.parse('./test.fbx', options, function(err, data){
    console.log(data, err)
  // do stuff with data 
});
```

**Comment by chrispalazzolo** [comment]
Is the test.fbx file binary or ascii?  This parser can only parse the ascii version of the fbx file format.

**Comment by stellanhaglund** [comment]
Oh i see, i will have to check that.

lördag 14 maj 2016 skrev Chris Palazzolo notifications@github.com:

**Comment by chrispalazzolo** [comment]
I pushed up a change where it checks the file and if its a binary it will throw an error and return that error.  You can update and see if that is the message you get back.  If not, then the fbx file might be malformed or the parser is getting tripped up on the file.
